In [1]:
! pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 136 kB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 22 kB/s eta 0:00:014
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aaradhychinche/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 73 kB/s eta 0:00:011
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 162 kB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Users/aaradhychinche/Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
import numpy as np

In [3]:
##pd.DataFrame() - from a dictionary
restraunt_data = {
    'table_no':[12,14,15],
    'bill_amount':[200,300,400],
    'waiter_name':['Amit','Priya','Rahul']

}
df = pd.DataFrame(restraunt_data)
print(df)
print(type(df))
print(df['bill_amount'])
print(type(df['bill_amount']))

   table_no  bill_amount waiter_name
0        12          200        Amit
1        14          300       Priya
2        15          400       Rahul
<class 'pandas.core.frame.DataFrame'>
0    200
1    300
2    400
Name: bill_amount, dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
#pd.Series()- 1D data with an index
total_bill = [4700,8000,5000,1200]
total_bill = pd.Series(total_bill, index = ['mon','tue','wed','fri'])
print(total_bill)
print(type(total_bill))

mon    4700
tue    8000
wed    5000
fri    1200
dtype: int64
<class 'pandas.core.series.Series'>

In [10]:
#.values/.to_numpy()
print(df['bill_amount'].values)
print(type(df['bill_amount'].values))
print(df['bill_amount'].to_numpy())
print(type(df['bill_amount'].to_numpy()))

[200 300 400]
<class 'numpy.ndarray'>
[200 300 400]
<class 'numpy.ndarray'>

In [14]:
#practice
price = [45,30,15,60]
price = pd.Series(price, index = ['pizza','burger','pasta','fries'])
print(price)
dic = {
    'brand':["nike","puma","campus"],
    'Price':[10,40,50],
    'In_stock':[True,False,True]
}
df = pd.DataFrame(dic)
print(df)

pizza     45
burger    30
pasta     15
fries     60
dtype: int64
    brand  Price  In_stock
0    nike     10      True
1    puma     40     False
2  campus     50      True
[10 40 50]

In [15]:
# get tabular data from a file
df = pd.read_csv('tip.csv')
print(df)
print(type(df))

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
<class 'pandas.core.frame.DataFrame'>

In [21]:
#head(), tail()
df.head()# by default it gives top 5 value
df.head(20)

df.tail() # by default it gives bottom 5 value

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [26]:
df.sample() # by default it gives 1 random value
df.sample(5) # this gives  5 random values

     total_bill   tip     sex smoker   day    time  size
182       45.35  3.50    Male    Yes   Sun  Dinner     3
107       25.21  4.29    Male    Yes   Sat  Dinner     2
39        31.27  5.00    Male     No   Sat  Dinner     3
143       27.05  5.00  Female     No  Thur   Lunch     6
71        17.07  3.00  Female     No   Sat  Dinner     3

In [29]:
#shape , columns
print(df.shape)
print(df.columns)

(244, 7)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [31]:
#info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [32]:
#describe() - statsitics of data
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [36]:
#value_counts(), unique() ,nunique()
print(df['day'].value_counts())
print()
print(df['day'].unique())
print()
df['day'].nunique()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

['Sun' 'Sat' 'Thur' 'Fri']

4